Content-Type: multipart/mixed; boundary="===============FTNT-VM==============="
MIME-Version: 1.0

--===============FTNT-VM===============
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="config"

config system global
    set hostname "${vm_name}"
end

%{ if license_flex != "" }
exec vm-license ${license_flex}
%{ endif }

%{ if license_file != "" }
--===============FTNT-VM===============
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="${license_file}"

${file(license_file)}

%{ endif }
--===============FTNT-VM===============
